<?php

return [
    [
        'key' => 'general.prayer_times',
        'name' => 'prayer_times::app.admin.system.title',
        'info' => 'prayer_times::app.admin.system.info',
        'icon' => 'settings/store.svg',
        'sort' => 8,
    ],
    [
        'key' => 'general.prayer_times.settings',
        'name' => 'prayer_times::app.admin.system.settings',
        'info' => 'prayer_times::app.admin.system.settings_info',
        'sort' => 1,
        'fields' => [
            [
                'name' => 'location_picker',
                'title' => 'prayer_times::app.admin.system.location_picker',
                'type' => 'blade',
                'path' => 'prayer_times::admin.location-picker',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'location_name',
                'title' => 'prayer_times::app.admin.system.location_name',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => true,
                'default' => 'مكة المكرمة',
                'info' => 'prayer_times::app.admin.system.location_name_info',
            ],
            [
                'name' => 'latitude',
                'title' => 'prayer_times::app.admin.system.latitude',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
                'default' => '21.4225',
            ],
            [
                'name' => 'longitude',
                'title' => 'prayer_times::app.admin.system.longitude',
                'type' => 'text',
                'channel_based' => true,
                'locale_based' => false,
                'default' => '39.8262',
            ],
            [
                'name' => 'timezone',
                'title' => 'prayer_times::app.admin.system.timezone',
                'type' => 'select',
                'channel_based' => true,
                'locale_based' => false,
                'default' => '+03:00',
                'info' => 'prayer_times::app.admin.system.timezone_info',
                'options' => 'NumbersNebula\PrayerTimes\Helpers\TimezoneHelper@getTimezoneOptions',
            ],
            [
                'name' => 'method',
                'title' => 'prayer_times::app.admin.system.method',
                'type' => 'select',
                'channel_based' => true,
                'locale_based' => false,
                'default' => '4',
                'options' => [
                    [
                        'title' => 'prayer_times::app.admin.system.method_0',
                        'value' => 0,
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.method_1',
                        'value' => 1,
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.method_2',
                        'value' => 2,
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.method_3',
                        'value' => 3,
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.method_4',
                        'value' => 4,
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.method_5',
                        'value' => 5,
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.method_7',
                        'value' => 7,
                    ],
                ],
            ],
        ],
    ],
    [
        'key' => 'general.prayer_times.appearance',
        'name' => 'prayer_times::app.admin.system.appearance.title',
        'info' => 'prayer_times::app.admin.system.appearance.info',
        'sort' => 2,
        'fields' => [
            [
                'name' => 'enable_bottom_bar',
                'title' => 'prayer_times::app.admin.system.appearance.enable_bottom_bar',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 1,
            ],
            [
                'name' => 'bottom_bar_position',
                'title' => 'prayer_times::app.admin.system.appearance.bottom_bar_position',
                'type' => 'select',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 'center',
                'options' => [
                    [
                        'title' => 'prayer_times::app.admin.system.appearance.position_center',
                        'value' => 'center',
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.appearance.position_right',
                        'value' => 'right',
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.appearance.position_left',
                        'value' => 'left',
                    ],
                ],
            ],
            [
                'name' => 'theme_preset',
                'title' => 'prayer_times::app.admin.system.appearance.theme_preset',
                'info' => 'prayer_times::app.admin.system.appearance.theme_preset_info',
                'type' => 'select',
                'channel_based' => true,
                'locale_based' => false,
                'default' => 'jz_luxury',
                'options' => [
                    [
                        'title' => 'prayer_times::app.admin.system.appearance.preset_jz_luxury',
                        'value' => 'jz_luxury',
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.appearance.preset_emerald_gold',
                        'value' => 'emerald_gold',
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.appearance.preset_classic_dark',
                        'value' => 'classic_dark',
                    ],
                    [
                        'title' => 'prayer_times::app.admin.system.appearance.preset_custom',
                        'value' => 'custom',
                    ],
                ],
            ],
            [
                'name' => 'primary_color',
                'title' => 'prayer_times::app.admin.system.appearance.primary_color',
                'info' => 'prayer_times::app.admin.system.appearance.primary_color_info',
                'type' => 'color',
                'channel_based' => true,
                'locale_based' => false,
                'default' => '#171717',
            ],
            [
                'name' => 'secondary_color',
                'title' => 'prayer_times::app.admin.system.appearance.secondary_color',
                'info' => 'prayer_times::app.admin.system.appearance.secondary_color_info',
                'type' => 'color',
                'channel_based' => true,
                'locale_based' => false,
                'default' => '#242424',
            ],
            [
                'name' => 'accent_color',
                'title' => 'prayer_times::app.admin.system.appearance.accent_color',
                'info' => 'prayer_times::app.admin.system.appearance.accent_color_info',
                'type' => 'color',
                'channel_based' => true,
                'locale_based' => false,
                'default' => '#c8a24d',
            ],
            [
                'name' => 'card_bg_color',
                'title' => 'prayer_times::app.admin.system.appearance.card_bg_color',
                'info' => 'prayer_times::app.admin.system.appearance.card_bg_color_info',
                'type' => 'color',
                'channel_based' => true,
                'locale_based' => false,
                'default' => '#1f1f1f',
            ],
            [
                'name' => 'text_color',
                'title' => 'prayer_times::app.admin.system.appearance.text_color',
                'info' => 'prayer_times::app.admin.system.appearance.text_color_info',
                'type' => 'color',
                'channel_based' => true,
                'locale_based' => false,
                'default' => '#ffffff',
            ],
        ],
    ],
];
